# Generated by Django 5.1.4 on 2026-08-14 11:19

import squallyline.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[squallyline.image_utils.validate_image_upload]),
        ),
    ]
