# Generated by Django 5.1.4 on 2026-08-14 11:19

import django.db.models.deletion
import squallyline.image_utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointmentproposal_proposalevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentproposal',
            old_name='reference_images',
            new_name='legacy_reference_urls',
        ),
        migrations.CreateModel(
            name='ProposalReferenceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='proposal_references/', validators=[squallyline.image_utils.validate_image_upload])),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='appointments.appointmentproposal')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
