# Generated by Django 5.1.4 on 2026-08-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointmentproposal_reference_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentproposal',
            name='legacy_reference_urls',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
