# Generated by Django 5.1.4 on 2026-08-14 11:19

import squallyline.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[squallyline.image_utils.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[squallyline.image_utils.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='productreviewimage',
            name='image',
            field=models.ImageField(upload_to='review_images/', validators=[squallyline.image_utils.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='image',
            field=models.ImageField(upload_to='styles/', validators=[squallyline.image_utils.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='stylereviewimage',
            name='image',
            field=models.ImageField(upload_to='style_review_images/', validators=[squallyline.image_utils.validate_image_upload]),
        ),
    ]
